backend:
  name: github
  [cite_start]repo: shreyagurung/daara-pari # Updated to your repo [cite: 178]
  branch: main

media_library:
  name: cloudinary
  config:
    [cite_start]cloud_name: dchfozs9d # Your cloud name [cite: 5]
    [cite_start]api_key: 718743584267132 # Your API Key [cite: 180]

collections:
  - name: "gallery"
    label: "Gallery"
    delete: false # Prevents accidental deletion of the file structure
    editor:
      preview: false
    files:
      - file: "content/gallery.json"
        label: "Gallery Data"
        name: "gallery_data"
        fields:
          - label: "Mudhouse"
            name: "mudhouse"
            widget: "list"
            summary: '{{fields.url}}'
            field: { label: "Image", name: "url", widget: "image" }
          - label: "Main House"
            name: "mainhouse"
            widget: "list"
            summary: '{{fields.url}}'
            field: { label: "Image", name: "url", widget: "image" }
          - label: "The Essentials"
            name: "essentials"
            widget: "list"
            summary: '{{fields.url}}'
            field: { label: "Image", name: "url", widget: "image" }
          - label: "The Wild"
            name: "wild"
            widget: "list"
            summary: '{{fields.url}}'
            field: { label: "Image", name: "url", widget: "image" }
          - label: "The Land"
            name: "land"
            widget: "list"
            summary: '{{fields.url}}'
            field: { label: "Image", name: "url", widget: "image" }
          - label: "The Spirit"
            name: "spirit"
            widget: "list"
            summary: '{{fields.url}}'
            field: { label: "Image", name: "url", widget: "image" }
          - label: "The Mind"
            name: "mind"
            widget: "list"
            summary: '{{fields.url}}'
            field: { label: "Image", name: "url", widget: "image" }